---
- name: Check PAN-OS schedule objects and related security rules
  hosts: panorama
  connection: local
  gather_facts: false
  
  vars:
    provider:
      ip_address: "{{ ip_address }}"
      username: "{{ username }}"
      password: "{{ password }}"
    warning_days: 7
      
  tasks:
    - name: Get current date and warning date
      ansible.builtin.set_fact:
        current_date: "{{ lookup('pipe', 'date +%Y/%m/%d') }}"
        warning_date: "{{ lookup('pipe', 'date -d \"+{{ warning_days }} days\" +%Y/%m/%d') }}"

    - name: Gather all schedule objects
      paloaltonetworks.panos.panos_schedule_object:
        provider: "{{ provider }}"
        state: "gathered"
        gathered_filter: '*'
      register: schedule_objects

    - name: Process and filter expiring schedules
      ansible.builtin.set_fact:
        expiring_schedules: "{{ lookup('template', 'templates/process_schedules.j2') }}"

    - name: Get expiring schedule names
      ansible.builtin.set_fact:
        expiring_schedule_names: "{{ expiring_schedules | map(attribute='name') | list }}"
      when: expiring_schedules|length > 0

    - name: Gather security rules
      paloaltonetworks.panos.panos_security_rule:
        provider: "{{ provider }}"
        state: "gathered"
        gathered_filter: '*'
      register: security_rules
      when: expiring_schedule_names is defined

    - name: Filter and organize affected rules
      ansible.builtin.set_fact:
        affected_rules_by_schedule: "{{ lookup('template', 'templates/process_rules.j2') }}"
      when: security_rules is defined and security_rules.gathered|length > 0